@hostname = localhost:8080

###

// Challenge
GET http://{{hostname}}/rhpds/test HTTP/1.1

###

// Challenge
POST http://{{hostname}}/rhpds/challenge HTTP/1.1
content-type: application/json

{
    "token": "Jhj5dZrVaK7ZwHHjRyZWjbDl",
    "challenge": "3eZbrw1aBm2rZgRNFdxV2595E9CY3gmdALWMmHkvFXO7tYXAYM8P",
    "type": "url_verification"
}

###
// Test help
POST http://{{hostname}}/rhpds HTTP/1.1
Content-Type: application/x-www-form-urlencoded

token=gIkuvaNzQIHg97ATvDxqgjtO
&team_id=T0001
&team_domain=example
&enterprise_id=E0001
&enterprise_name=Globular%20Construct%20Inc
&channel_id=C2147483705
&channel_name=test
&user_id=U2147483697
&user_name=Steve
&command=/rhpds_envs
&text=help%20add
&response_url=https://hooks.slack.com/commands/1234/5678
&trigger_id=13345224609.738474920.8088930838d88f008e0

###
// Test add with OCP3 URL
POST http://{{hostname}}/rhpds HTTP/1.1
Content-Type: application/x-www-form-urlencoded

token=gIkuvaNzQIHg97ATvDxqgjtO
&team_id=T0001
&team_domain=example
&enterprise_id=E0001
&enterprise_name=Globular%20Construct%20Inc
&channel_id=C2147483705
&channel_name=test
&user_id=U2147483697
&user_name=Steve
&command=/rhpds_envs
&text=add%20%3Chttps%3A%2F%2Fmaster.osevg-ec5b.openshiftworkshop.com%2Fconsole%3E
&response_url=https://hooks.slack.com/commands/1234/5678
&trigger_id=13345224609.738474920.8088930838d88f008e0

###
// Test add with OCP4 URL
POST http://{{hostname}}/rhpds HTTP/1.1
Content-Type: application/x-www-form-urlencoded

token=gIkuvaNzQIHg97ATvDxqgjtO
&team_id=T0001
&team_domain=example
&enterprise_id=E0001
&enterprise_name=Globular%20Construct%20Inc
&channel_id=C2147483705
&channel_name=test
&user_id=U2147483697
&user_name=Steve
&command=/rhpds_envs
&text=add%20%3Chttps%3A%2F%2Fconsole-openshift-console.apps.cluster-3730.3730.openshiftworkshop.com%2Fconsole%3E
&response_url=https://hooks.slack.com/commands/1234/5678
&trigger_id=13345224609.738474920.8088930838d88f008e0

### 
// Test add with unknown
POST http://{{hostname}}/rhpds HTTP/1.1
Content-Type: application/x-www-form-urlencoded

token=gIkuvaNzQIHg97ATvDxqgjtO
&team_id=T0001
&team_domain=example
&enterprise_id=E0001
&enterprise_name=Globular%20Construct%20Inc
&channel_id=C2147483705
&channel_name=test
&user_id=U2147483697
&user_name=Steve
&command=/rhpds_envs
&text=add%20%3Chttps%3A%2F%2Fmaster.openshiftlabs.io%3E
&response_url=https://hooks.slack.com/commands/1234/5678
&trigger_id=13345224609.738474920.8088930838d88f008e0

### 
// Test list
POST http://{{hostname}}/rhpds HTTP/1.1
Content-Type: application/x-www-form-urlencoded

token=gIkuvaNzQIHg97ATvDxqgjtO
&team_id=T0001
&team_domain=example
&enterprise_id=E0001
&enterprise_name=Globular%20Construct%20Inc
&channel_id=C2147483705
&channel_name=test
&user_id=U2147483697
&user_name=Steve
&command=/rhpds_envs
&text=list
&response_url=https://hooks.slack.com/commands/1234/5678
&trigger_id=13345224609.738474920.8088930838d88f008e0

### 
// Test delete
POST http://{{hostname}}/rhpds HTTP/1.1
Content-Type: application/x-www-form-urlencoded

token=gIkuvaNzQIHg97ATvDxqgjtO
&team_id=T0001
&team_domain=example
&enterprise_id=E0001
&enterprise_name=Globular%20Construct%20Inc
&channel_id=C2147483705
&channel_name=test
&user_id=U2147483697
&user_name=Steve
&command=/rhpds_envs
&text=delete%20osevg-ec5b
&response_url=https://hooks.slack.com/commands/1234/5678
&trigger_id=13345224609.738474920.8088930838d88f008e0


### 
// Test verify
POST http://{{hostname}}/rhpds HTTP/1.1
Content-Type: application/x-www-form-urlencoded

token=gIkuvaNzQIHg97ATvDxqgjtO
&team_id=T0001
&team_domain=example
&enterprise_id=E0001
&enterprise_name=Globular%20Construct%20Inc
&channel_id=C2147483705
&channel_name=test
&user_id=U2147483697
&user_name=Steve
&command=/rhpds_envs
&text=verify%20osevg-ec5b
&response_url=https://hooks.slack.com/commands/1234/5678
&trigger_id=13345224609.738474920.8088930838d88f008e0